export const data = [
  { name: 'EU Aegwynn', id: 3679 },
  { name: 'EU Aerie Peak', id: 1416 },
  { name: 'EU Agamaggan', id: 1091 },
  { name: 'EU Aggra (Portuguus)', id: 1303 },
  { name: 'EU Aggramar', id: 1325 },
  { name: "EU Ahn'Qiraj", id: 1598 },
  { name: "EU Al'Akir", id: 3713 },
  { name: 'EU Alexstrasza', id: 3696 },
  { name: 'EU Alleria', id: 1099 },
  { name: 'EU Alonsus', id: 1082 },
  { name: "EU Aman'Thul", id: 1105 },
  { name: 'EU Ambossar', id: 604 },
  { name: 'EU Anachronos', id: 1082 },
  { name: 'EU Anetheron', id: 1104 },
  { name: 'EU Antonidas', id: 3686 },
  { name: "EU Anub'arak", id: 1105 },
  { name: 'EU Arak-arahm', id: 512 },
  { name: 'EU Arathi', id: 1624 },
  { name: 'EU Arathor', id: 1587 },
  { name: 'EU Archimonde', id: 1302 },
  { name: 'EU Area 52', id: 1400 },
  { name: 'EU Argent Dawn', id: 3702 },
  { name: 'EU Arthas', id: 578 },
  { name: 'EU Arygos', id: 1406 },
  { name: 'EU Ashenvale', id: 1923 },
  { name: 'EU Aszune', id: 3666 },
  { name: 'EU Auchindoun', id: 1597 },
  { name: 'EU Azjol-Nerub', id: 1396 },
  { name: 'EU Azshara', id: 570 },
  { name: 'EU Azuregos', id: 1922 },
  { name: 'EU Azuremyst', id: 1417 },
  { name: 'EU Baelgun', id: 570 },
  { name: 'EU Balnazzar', id: 1598 },
  { name: 'EU Blackhand', id: 3691 },
  { name: 'EU Blackmoore', id: 580 },
  { name: 'EU Blackrock', id: 581 },
  { name: 'EU Blackscar', id: 1929 },
  { name: "EU Blade's Edge", id: 1416 },
  { name: 'EU Bladefist', id: 3657 },
  { name: 'EU Bloodfeather', id: 633 },
  { name: 'EU Bloodhoof', id: 1080 },
  { name: 'EU Bloodscalp', id: 1091 },
  { name: 'EU Blutkessel', id: 578 },
  { name: 'EU Booty Bay', id: 1929 },
  { name: 'EU Borean Tundra', id: 1929 },
  { name: 'EU Boulderfist', id: 1598 },
  { name: 'EU Bronze Dragonflight', id: 1393 },
  { name: 'EU Bronzebeard', id: 1416 },
  { name: 'EU Burning Blade', id: 1092 },
  { name: 'EU Burning Legion', id: 3713 },
  { name: 'EU Burning Steppes', id: 633 },
  { name: "EU C'Thun", id: 1378 },
  { name: 'EU Chamber of Aspects', id: 1307 },
  { name: 'EU Chants eternels', id: 510 },
  { name: "EU Cho'gall", id: 1621 },
  { name: 'EU Chromaggus', id: 1598 },
  { name: 'EU Colinas Pardas', id: 1384 },
  { name: 'EU Confrerie du Thorium', id: 1127 },
  { name: 'EU Conseil des Ombres', id: 1127 },
  { name: 'EU Crushridge', id: 1091 },
  { name: 'EU Culte de la Rive noire', id: 1127 },
  { name: 'EU Daggerspine', id: 1598 },
  { name: 'EU Dalaran', id: 1621 },
  { name: 'EU Dalvengyr', id: 1105 },
  { name: 'EU Darkmoon Faire', id: 1096 },
  { name: 'EU Darksorrow', id: 3657 },
  { name: 'EU Darkspear', id: 633 },
  { name: 'EU Das Konsortium', id: 1121 },
  { name: 'EU Das Syndikat', id: 1121 },
  { name: 'EU Deathguard', id: 1605 },
  { name: 'EU Deathweaver', id: 1929 },
  { name: 'EU Deathwing', id: 1596 },
  { name: 'EU Deepholm', id: 1614 },
  { name: 'EU Defias Brotherhood', id: 1096 },
  { name: 'EU Dentarg', id: 1084 },
  { name: 'EU Der Mithrilorden', id: 1405 },
  { name: 'EU Der Rat von Dalaran', id: 1405 },
  { name: 'EU Der abyssische Rat', id: 1121 },
  { name: 'EU Destromath', id: 612 },
  { name: 'EU Dethecus', id: 531 },
  { name: 'EU Die Aldor', id: 1618 },
  { name: 'EU Die Arguswacht', id: 1121 },
  { name: 'EU Die Nachtwache', id: 1405 },
  { name: 'EU Die Silberne Hand', id: 1121 },
  { name: 'EU Die Todeskrallen', id: 1121 },
  { name: 'EU Die ewige Wacht', id: 1121 },
  { name: 'EU Doomhammer', id: 1402 },
  { name: 'EU Draenor', id: 1403 },
  { name: 'EU Dragonblight', id: 1596 },
  { name: 'EU Dragonmaw', id: 3656 },
  { name: "EU Drak'thul", id: 1092 },
  { name: "EU Drek'Thar", id: 1122 },
  { name: 'EU Dun Modr', id: 1378 },
  { name: 'EU Dun Morogh', id: 1408 },
  { name: 'EU Dunemaul', id: 1597 },
  { name: 'EU Durotan', id: 578 },
  { name: 'EU Earthen Ring', id: 1096 },
  { name: 'EU Echsenkessel', id: 3691 },
  { name: 'EU Eitrigg', id: 1122 },
  { name: "EU Eldre'Thalas", id: 1621 },
  { name: 'EU Elune', id: 1315 },
  { name: 'EU Emerald Dream', id: 2074 },
  { name: 'EU Emeriss', id: 1091 },
  { name: 'EU Eonar', id: 1416 },
  { name: 'EU Eredar', id: 3692 },
  { name: 'EU Eversong', id: 1925 },
  { name: 'EU Executus', id: 633 },
  { name: 'EU Exodar', id: 1385 },
  { name: 'EU Festung der Sturme', id: 1104 },
  { name: 'EU Fordragon', id: 1623 },
  { name: 'EU Forscherliga', id: 1405 },
  { name: 'EU Frostmane', id: 1303 },
  { name: 'EU Frostmourne', id: 1105 },
  { name: 'EU Frostwhisper', id: 3657 },
  { name: 'EU Frostwolf', id: 3703 },
  { name: 'EU Galakrond', id: 1614 },
  { name: 'EU Garona', id: 509 },
  { name: 'EU Garrosh', id: 1401 },
  { name: 'EU Genjuros', id: 3657 },
  { name: 'EU Ghostlands', id: 1596 },
  { name: 'EU Gilneas', id: 612 },
  { name: 'EU Goldrinn', id: 1928 },
  { name: 'EU Gordunni', id: 1602 },
  { name: 'EU Gorgonnash', id: 612 },
  { name: 'EU Greymane', id: 1928 },
  { name: 'EU Grim Batol', id: 1303 },
  { name: 'EU Grom', id: 1929 },
  { name: "EU Gul'dan", id: 1104 },
  { name: 'EU Hakkar', id: 1091 },
  { name: 'EU Haomarush', id: 3656 },
  { name: 'EU Hellfire', id: 1587 },
  { name: 'EU Hellscream', id: 1325 },
  { name: 'EU Howling Fjord', id: 1615 },
  { name: 'EU Hyjal', id: 1390 },
  { name: 'EU Illidan', id: 1624 },
  { name: 'EU Jaedenar', id: 1597 },
  { name: "EU Kael'thas", id: 512 },
  { name: 'EU Karazhan', id: 1596 },
  { name: 'EU Kargath', id: 604 },
  { name: 'EU Kazzak', id: 1305 },
  { name: "EU Kel'Thuzad", id: 578 },
  { name: 'EU Khadgar', id: 1080 },
  { name: 'EU Khaz Modan', id: 3690 },
  { name: "EU Khaz'goroth", id: 1406 },
  { name: "EU Kil'jaeden", id: 1104 },
  { name: 'EU Kilrogg', id: 1587 },
  { name: 'EU Kirin Tor', id: 1127 },
  { name: "EU Kor'gall", id: 633 },
  { name: "EU Krag'jin", id: 570 },
  { name: 'EU Krasus', id: 1122 },
  { name: 'EU Kul Tiras', id: 1082 },
  { name: 'EU Kult der Verdammten', id: 1121 },
  { name: 'EU La Croisade ecarlate', id: 1127 },
  { name: 'EU Laughing Skull', id: 1598 },
  { name: 'EU Les Clairvoyants', id: 1127 },
  { name: 'EU Les Sentinelles', id: 1127 },
  { name: 'EU Lich King', id: 1928 },
  { name: 'EU Lightbringer', id: 1388 },
  { name: "EU Lightning's Blade", id: 1596 },
  { name: 'EU Lordaeron', id: 580 },
  { name: 'EU Los Errantes', id: 1384 },
  { name: 'EU Lothar', id: 570 },
  { name: 'EU Madmortem', id: 3696 },
  { name: 'EU Magtheridon', id: 3681 },
  { name: "EU Mal'Ganis", id: 3691 },
  { name: 'EU Malfurion', id: 1098 },
  { name: 'EU Malorne', id: 1097 },
  { name: 'EU Malygos', id: 1098 },
  { name: 'EU Mannoroth', id: 612 },
  { name: 'EU Marecage de Zangar', id: 1621 },
  { name: 'EU Mazrigos', id: 1388 },
  { name: 'EU Medivh', id: 1331 },
  { name: 'EU Minahonda', id: 1385 },
  { name: 'EU Moonglade', id: 1085 },
  { name: "EU Mug'thol", id: 531 },
  { name: 'EU Nagrand', id: 1587 },
  { name: 'EU Nathrezim', id: 1104 },
  { name: 'EU Naxxramas', id: 1624 },
  { name: 'EU Nazjatar', id: 1105 },
  { name: 'EU Nefarian', id: 612 },
  { name: 'EU Nemesis', id: 1316 },
  { name: 'EU Neptulon', id: 3657 },
  { name: "EU Ner'zhul", id: 509 },
  { name: "EU Nera'thor", id: 612 },
  { name: 'EU Nethersturm', id: 3696 },
  { name: 'EU Nordrassil', id: 1393 },
  { name: 'EU Norgannon', id: 1408 },
  { name: 'EU Nozdormu', id: 1401 },
  { name: 'EU Onyxia', id: 531 },
  { name: 'EU Outland', id: 1301 },
  { name: 'EU Perenolde', id: 1401 },
  { name: "EU Pozzo dell'Eternita", id: 1309 },
  { name: 'EU Proudmoore', id: 3696 },
  { name: "EU Quel'Thalas", id: 1396 },
  { name: 'EU Ragnaros', id: 3682 },
  { name: 'EU Rajaxx', id: 1104 },
  { name: 'EU Rashgarroth', id: 512 },
  { name: 'EU Ravencrest', id: 1329 },
  { name: 'EU Ravenholdt', id: 1096 },
  { name: 'EU Razuvious', id: 1614 },
  { name: 'EU Rexxar', id: 1099 },
  { name: 'EU Runetotem', id: 1587 },
  { name: 'EU Sanguino', id: 1379 },
  { name: 'EU Sargeras', id: 509 },
  { name: 'EU Saurfang', id: 633 },
  { name: 'EU Scarshield Legion', id: 1096 },
  { name: "EU Sen'jin", id: 1400 },
  { name: 'EU Shadowsong', id: 3666 },
  { name: 'EU Shattered Halls', id: 1598 },
  { name: 'EU Shattered Hand', id: 633 },
  { name: 'EU Shattrath', id: 1401 },
  { name: "EU Shen'dralar", id: 1379 },
  { name: 'EU Silvermoon', id: 3391 },
  { name: 'EU Sinstralis', id: 1621 },
  { name: 'EU Skullcrusher', id: 3713 },
  { name: 'EU Soulflayer', id: 1604 },
  { name: 'EU Spinebreaker', id: 3656 },
  { name: 'EU Sporeggar', id: 1096 },
  { name: 'EU Steamwheedle Cartel', id: 1085 },
  { name: 'EU Stormrage', id: 1417 },
  { name: 'EU Stormreaver', id: 3656 },
  { name: 'EU Stormscale', id: 2073 },
  { name: 'EU Sunstrider', id: 1598 },
  { name: 'EU Suramar', id: 1331 },
  { name: 'EU Sylvanas', id: 1597 },
  { name: 'EU Taerar', id: 3691 },
  { name: 'EU Talnivarr', id: 1598 },
  { name: 'EU Tarren Mill', id: 1084 },
  { name: 'EU Teldrassil', id: 1401 },
  { name: 'EU Temple noir', id: 1624 },
  { name: 'EU Terenas', id: 2074 },
  { name: 'EU Terokkar', id: 633 },
  { name: 'EU Terrordar', id: 531 },
  { name: 'EU The Maelstrom', id: 1596 },
  { name: "EU The Sha'tar", id: 1085 },
  { name: 'EU The Venture Co', id: 1096 },
  { name: 'EU Theradras', id: 531 },
  { name: 'EU Thermaplugg', id: 1929 },
  { name: 'EU Thrall', id: 604 },
  { name: "EU Throk'Feroth", id: 512 },
  { name: 'EU Thunderhorn', id: 1313 },
  { name: 'EU Tichondrius', id: 580 },
  { name: 'EU Tirion', id: 578 },
  { name: 'EU Todeswache', id: 1405 },
  { name: 'EU Trollbane', id: 1598 },
  { name: 'EU Turalyon', id: 1402 },
  { name: "EU Twilight's Hammer", id: 1091 },
  { name: 'EU Twisting Nether', id: 3674 },
  { name: 'EU Tyrande', id: 1384 },
  { name: 'EU Uldaman', id: 1122 },
  { name: 'EU Ulduar', id: 612 },
  { name: 'EU Uldum', id: 1379 },
  { name: "EU Un'Goro", id: 1400 },
  { name: 'EU Varimathras', id: 1315 },
  { name: 'EU Vashj', id: 3656 },
  { name: "EU Vek'lor", id: 578 },
  { name: "EU Vek'nilash", id: 1416 },
  { name: "EU Vol'jin", id: 510 },
  { name: 'EU Wildhammer', id: 1313 },
  { name: 'EU Wrathbringer', id: 578 },
  { name: 'EU Xavius', id: 3713 },
  { name: 'EU Ysera', id: 1097 },
  { name: 'EU Ysondre', id: 1335 },
  { name: 'EU Zenedar', id: 3657 },
  { name: 'EU Zirkel des Cenarius', id: 1405 },
  { name: "EU Zul'jin", id: 1379 },
  { name: 'EU Zuluhed', id: 1105 },
  { name: 'US Aegwynn', id: 1136 },
  { name: 'US Aerie Peak', id: 1426 },
  { name: 'US Agamaggan', id: 1129 },
  { name: 'US Aggramar', id: 106 },
  { name: 'US Akama', id: 84 },
  { name: 'US Alexstrasza', id: 1070 },
  { name: 'US Alleria', id: 52 },
  { name: 'US Altar of Storms', id: 78 },
  { name: 'US Alterac Mountains', id: 71 },
  { name: "US Aman'Thul", id: 3726 },
  { name: 'US Andorhal', id: 96 },
  { name: 'US Anetheron', id: 78 },
  { name: 'US Antonidas', id: 84 },
  { name: "US Anub'arak", id: 1138 },
  { name: 'US Anvilmar', id: 71 },
  { name: 'US Arathor', id: 1138 },
  { name: 'US Archimonde', id: 1129 },
  { name: 'US Area 52', id: 3676 },
  { name: 'US Argent Dawn', id: 75 },
  { name: 'US Arthas', id: 69 },
  { name: 'US Arygos', id: 99 },
  { name: 'US Auchindoun', id: 67 },
  { name: 'US Azgalor', id: 77 },
  { name: 'US Azjol-Nerub', id: 121 },
  { name: 'US Azralon', id: 3209 },
  { name: 'US Azshara', id: 77 },
  { name: 'US Azuremyst', id: 160 },
  { name: 'US Baelgun', id: 1190 },
  { name: 'US Balnazzar', id: 71 },
  { name: 'US Barthilas', id: 3723 },
  { name: 'US Black Dragonflight', id: 96 },
  { name: 'US Blackhand', id: 54 },
  { name: 'US Blackrock', id: 121 },
  { name: 'US Blackwater Raiders', id: 125 },
  { name: 'US Blackwing Lair', id: 154 },
  { name: "US Blade's Edge", id: 1129 },
  { name: 'US Bladefist', id: 1147 },
  { name: 'US Bleeding Hollow', id: 73 },
  { name: 'US Blood Furnace', id: 77 },
  { name: 'US Bloodhoof', id: 64 },
  { name: 'US Bloodscalp', id: 1185 },
  { name: 'US Bonechewer', id: 1136 },
  { name: 'US Borean Tundra', id: 86 },
  { name: 'US Boulderfist', id: 1185 },
  { name: 'US Bronzebeard', id: 117 },
  { name: 'US Burning Blade', id: 104 },
  { name: 'US Burning Legion', id: 1129 },
  { name: 'US Caelestrasz', id: 3721 },
  { name: 'US Cairne', id: 1168 },
  { name: 'US Cenarion Circle', id: 125 },
  { name: 'US Cenarius', id: 1168 },
  { name: "US Cho'gall", id: 67 },
  { name: 'US Chromaggus', id: 1138 },
  { name: 'US Coilfang', id: 157 },
  { name: 'US Crushridge', id: 1138 },
  { name: 'US Daggerspine', id: 1136 },
  { name: 'US Dalaran', id: 3683 },
  { name: 'US Dalvengyr', id: 157 },
  { name: 'US Dark Iron', id: 157 },
  { name: 'US Darkspear', id: 120 },
  { name: 'US Darrowmere', id: 113 },
  { name: "US Dath'Remar", id: 3726 },
  { name: 'US Dawnbringer', id: 160 },
  { name: 'US Deathwing', id: 155 },
  { name: 'US Demon Soul', id: 157 },
  { name: 'US Dentarg', id: 55 },
  { name: 'US Destromath', id: 77 },
  { name: 'US Dethecus', id: 154 },
  { name: 'US Detheroc', id: 154 },
  { name: 'US Doomhammer', id: 1190 },
  { name: 'US Draenor', id: 115 },
  { name: 'US Dragonblight', id: 114 },
  { name: 'US Dragonmaw', id: 84 },
  { name: "US Drak'Tharon", id: 127 },
  { name: "US Drak'thul", id: 86 },
  { name: 'US Draka', id: 113 },
  { name: 'US Drakkari', id: 1425 },
  { name: 'US Dreadmaul', id: 3725 },
  { name: 'US Drenden', id: 1138 },
  { name: 'US Dunemaul', id: 1185 },
  { name: 'US Durotan', id: 63 },
  { name: 'US Duskwood', id: 64 },
  { name: 'US Earthen Ring', id: 100 },
  { name: 'US Echo Isles', id: 115 },
  { name: 'US Eitrigg', id: 47 },
  { name: "US Eldre'Thalas", id: 84 },
  { name: 'US Elune', id: 67 },
  { name: 'US Emerald Dream', id: 162 },
  { name: 'US Eonar', id: 96 },
  { name: 'US Eredar', id: 53 },
  { name: 'US Executus', id: 155 },
  { name: 'US Exodar', id: 52 },
  { name: 'US Farstriders', id: 12 },
  { name: 'US Feathermoon', id: 118 },
  { name: 'US Fenris', id: 114 },
  { name: 'US Firetree', id: 127 },
  { name: 'US Fizzcrank', id: 106 },
  { name: 'US Frostmane', id: 1168 },
  { name: 'US Frostmourne', id: 3725 },
  { name: 'US Frostwolf', id: 127 },
  { name: 'US Galakrond', id: 54 },
  { name: 'US Gallywix', id: 3234 },
  { name: 'US Garithos', id: 1138 },
  { name: 'US Garona', id: 104 },
  { name: 'US Garrosh', id: 1136 },
  { name: 'US Ghostlands', id: 1175 },
  { name: 'US Gilneas', id: 67 },
  { name: 'US Gnomeregan', id: 1175 },
  { name: 'US Goldrinn', id: 3207 },
  { name: 'US Gorefiend', id: 53 },
  { name: 'US Gorgonnash', id: 71 },
  { name: 'US Greymane', id: 158 },
  { name: 'US Grizzly Hills', id: 1175 },
  { name: "US Gul'dan", id: 96 },
  { name: 'US Gundrak', id: 3725 },
  { name: 'US Gurubashi', id: 1136 },
  { name: 'US Hakkar', id: 1136 },
  { name: 'US Haomarush', id: 154 },
  { name: 'US Hellscream', id: 53 },
  { name: 'US Hydraxis', id: 86 },
  { name: 'US Hyjal', id: 3661 },
  { name: 'US Icecrown', id: 104 },
  { name: 'US Illidan', id: 57 },
  { name: 'US Jaedenar', id: 1129 },
  { name: "US Jubei'Thos", id: 3725 },
  { name: "US Kael'thas", id: 1175 },
  { name: 'US Kalecgos', id: 155 },
  { name: 'US Kargath', id: 1129 },
  { name: "US Kel'Thuzad", id: 3693 },
  { name: 'US Khadgar', id: 52 },
  { name: 'US Khaz Modan', id: 121 },
  { name: "US Khaz'goroth", id: 3726 },
  { name: "US Kil'jaeden", id: 9 },
  { name: 'US Kilrogg', id: 4 },
  { name: 'US Kirin Tor', id: 1071 },
  { name: 'US Korgath', id: 1168 },
  { name: 'US Korialstrasz', id: 84 },
  { name: 'US Kul Tiras', id: 1147 },
  { name: 'US Laughing Skull', id: 67 },
  { name: 'US Lethon', id: 154 },
  { name: 'US Lightbringer', id: 3694 },
  { name: "US Lightning's Blade", id: 104 },
  { name: 'US Lightninghoof', id: 163 },
  { name: 'US Llane', id: 99 },
  { name: 'US Lothar', id: 1175 },
  { name: 'US Madoran', id: 160 },
  { name: 'US Maelstrom', id: 163 },
  { name: 'US Magtheridon', id: 78 },
  { name: 'US Maiev', id: 1185 },
  { name: "US Mal'Ganis", id: 3684 },
  { name: 'US Malfurion', id: 1175 },
  { name: 'US Malorne', id: 127 },
  { name: 'US Malygos', id: 104 },
  { name: 'US Mannoroth', id: 77 },
  { name: 'US Medivh', id: 52 },
  { name: 'US Misha', id: 1151 },
  { name: "US Mok'Nathal", id: 86 },
  { name: 'US Moon Guard', id: 3675 },
  { name: 'US Moonrunner', id: 1175 },
  { name: "US Mug'thol", id: 84 },
  { name: 'US Muradin', id: 121 },
  { name: 'US Nagrand', id: 3721 },
  { name: 'US Nathrezim', id: 1138 },
  { name: 'US Nazgrel', id: 1184 },
  { name: 'US Nazjatar', id: 77 },
  { name: 'US Nemesis', id: 3208 },
  { name: "US Ner'zhul", id: 1168 },
  { name: 'US Nesingwary', id: 1184 },
  { name: 'US Nordrassil', id: 121 },
  { name: 'US Norgannon', id: 1129 },
  { name: 'US Onyxia', id: 104 },
  { name: 'US Perenolde', id: 1168 },
  { name: 'US Proudmoore', id: 5 },
  { name: "US Quel'Thalas", id: 1428 },
  { name: "US Quel'dorei", id: 1185 },
  { name: 'US Ragnaros', id: 1427 },
  { name: 'US Ravencrest', id: 1072 },
  { name: 'US Ravenholdt', id: 163 },
  { name: 'US Rexxar', id: 1151 },
  { name: 'US Rivendare', id: 127 },
  { name: 'US Runetotem', id: 151 },
  { name: 'US Sargeras', id: 76 },
  { name: 'US Saurfang', id: 3721 },
  { name: 'US Scarlet Crusade', id: 118 },
  { name: 'US Scilla', id: 96 },
  { name: "US Sen'jin", id: 1185 },
  { name: 'US Sentinels', id: 1071 },
  { name: 'US Shadow Council', id: 125 },
  { name: 'US Shadowmoon', id: 154 },
  { name: 'US Shadowsong', id: 86 },
  { name: 'US Shandris', id: 117 },
  { name: 'US Shattered Halls', id: 155 },
  { name: 'US Shattered Hand', id: 157 },
  { name: "US Shu'halo", id: 47 },
  { name: 'US Silver Hand', id: 12 },
  { name: 'US Silvermoon', id: 86 },
  { name: 'US Sisters of Elune', id: 125 },
  { name: 'US Skullcrusher', id: 96 },
  { name: 'US Skywall', id: 86 },
  { name: 'US Smolderthorn', id: 1138 },
  { name: 'US Spinebreaker', id: 53 },
  { name: 'US Spirestone', id: 127 },
  { name: 'US Staghelm', id: 160 },
  { name: 'US Steamwheedle Cartel', id: 1071 },
  { name: 'US Stonemaul', id: 1185 },
  { name: 'US Stormrage', id: 60 },
  { name: 'US Stormreaver', id: 58 },
  { name: 'US Stormscale', id: 127 },
  { name: 'US Suramar', id: 113 },
  { name: 'US Tanaris', id: 158 },
  { name: 'US Terenas', id: 86 },
  { name: 'US Terokkar', id: 1070 },
  { name: 'US Thaurissan', id: 3725 },
  { name: 'US The Forgotten Coast', id: 71 },
  { name: 'US The Scryers', id: 75 },
  { name: 'US The Underbog', id: 1129 },
  { name: 'US The Venture Co', id: 163 },
  { name: 'US Thorium Brotherhood', id: 12 },
  { name: 'US Thrall', id: 3678 },
  { name: 'US Thunderhorn', id: 1129 },
  { name: 'US Thunderlord', id: 77 },
  { name: 'US Tichondrius', id: 11 },
  { name: 'US Tol Barad', id: 3208 },
  { name: 'US Tortheldrin', id: 1168 },
  { name: 'US Trollbane', id: 1175 },
  { name: 'US Turalyon', id: 3685 },
  { name: 'US Twisting Nether', id: 163 },
  { name: 'US Uldaman', id: 1072 },
  { name: 'US Uldum', id: 84 },
  { name: 'US Undermine', id: 71 },
  { name: 'US Ursin', id: 96 },
  { name: 'US Uther', id: 151 },
  { name: 'US Vashj', id: 127 },
  { name: "US Vek'nilash", id: 1184 },
  { name: 'US Velen', id: 96 },
  { name: 'US Warsong', id: 71 },
  { name: 'US Whisperwind', id: 55 },
  { name: 'US Wildhammer', id: 53 },
  { name: 'US Windrunner', id: 113 },
  { name: 'US Winterhoof', id: 4 },
  { name: 'US Wyrmrest Accord', id: 1171 },
  { name: 'US Ysera', id: 63 },
  { name: 'US Ysondre', id: 78 },
  { name: 'US Zangarmarsh', id: 53 },
  { name: "US Zul'jin", id: 61 },
  { name: 'US Zuluhed', id: 96 }
]

export const findWoWServersIdByName = (term: string) => {
  return data.filter(({ name }) =>
    name.toLowerCase().includes(term.toLowerCase())
  )
}

export const findWoWServerByID = (idToFind: number) => {
  return data.find(({ id }) => id === idToFind)
}
