import type { WoWServerData, WoWServerRegion } from '~/requests/WoW/types'

export const NAdata: Array<WoWServerData> = [
  { name: 'Thrall', id: 3678 },
  { name: 'Azjol-Nerub', id: 121 },
  { name: 'Muradin', id: 121 },
  { name: 'Nordrassil', id: 121 },
  { name: 'Blackrock', id: 121 },
  { name: 'Khaz Modan', id: 121 },
  { name: 'Firetree', id: 127 },
  { name: "Drak'Tharon", id: 127 },
  { name: 'Rivendare', id: 127 },
  { name: 'Vashj', id: 127 },
  { name: 'Spirestone', id: 127 },
  { name: 'Malorne', id: 127 },
  { name: 'Frostwolf', id: 127 },
  { name: 'Stormscale', id: 127 },
  { name: 'Runetotem', id: 151 },
  { name: 'Uther', id: 151 },
  { name: 'Draenor', id: 115 },
  { name: 'Echo Isles', id: 115 },
  { name: 'Aggramar', id: 106 },
  { name: 'Fizzcrank', id: 106 },
  { name: 'Ravencrest', id: 1072 },
  { name: 'Uldaman', id: 1072 },
  { name: 'Stormreaver', id: 58 },
  { name: 'Elune', id: 67 },
  { name: 'Laughing Skull', id: 67 },
  { name: 'Auchindoun', id: 67 },
  { name: "Cho'gall", id: 67 },
  { name: 'Gilneas', id: 67 },
  { name: 'Bleeding Hollow', id: 73 },
  { name: 'Trollbane', id: 1175 },
  { name: 'Grizzly Hills', id: 1175 },
  { name: 'Malfurion', id: 1175 },
  { name: 'Lothar', id: 1175 },
  { name: "Kael'thas", id: 1175 },
  { name: 'Gnomeregan', id: 1175 },
  { name: 'Moonrunner', id: 1175 },
  { name: 'Ghostlands', id: 1175 },
  { name: "Vek'nilash", id: 1184 },
  { name: 'Nazgrel', id: 1184 },
  { name: 'Nesingwary', id: 1184 },
  { name: "Sen'jin", id: 1185 },
  { name: 'Dunemaul', id: 1185 },
  { name: 'Maiev', id: 1185 },
  { name: 'Bloodscalp', id: 1185 },
  { name: "Quel'dorei", id: 1185 },
  { name: 'Boulderfist', id: 1185 },
  { name: 'Stonemaul', id: 1185 },
  { name: 'Argent Dawn', id: 75 },
  { name: 'The Scryers', id: 75 },
  { name: 'Dragonmaw', id: 84 },
  { name: 'Uldum', id: 84 },
  { name: 'Akama', id: 84 },
  { name: 'Korialstrasz', id: 84 },
  { name: "Eldre'Thalas", id: 84 },
  { name: "Mug'thol", id: 84 },
  { name: 'Antonidas', id: 84 },
  { name: 'Silvermoon', id: 86 },
  { name: 'Skywall', id: 86 },
  { name: 'Terenas', id: 86 },
  { name: 'Hydraxis', id: 86 },
  { name: "Drak'thul", id: 86 },
  { name: 'Borean Tundra', id: 86 },
  { name: "Mok'Nathal", id: 86 },
  { name: 'Shadowsong', id: 86 },
  { name: 'Eonar', id: 96 },
  { name: 'Skullcrusher', id: 96 },
  { name: "Gul'dan", id: 96 },
  { name: 'Zuluhed', id: 96 },
  { name: 'Ursin', id: 96 },
  { name: 'Andorhal', id: 96 },
  { name: 'Black Dragonflight', id: 96 },
  { name: 'Velen', id: 96 },
  { name: 'Scilla', id: 96 },
  { name: 'Llane', id: 99 },
  { name: 'Arygos', id: 99 },
  { name: 'Earthen Ring', id: 100 },
  { name: 'Malygos', id: 104 },
  { name: 'Garona', id: 104 },
  { name: "Lightning's Blade", id: 104 },
  { name: 'Icecrown', id: 104 },
  { name: 'Onyxia', id: 104 },
  { name: 'Burning Blade', id: 104 },
  { name: 'Dragonblight', id: 114 },
  { name: 'Fenris', id: 114 },
  { name: 'Hellscream', id: 53 },
  { name: 'Gorefiend', id: 53 },
  { name: 'Spinebreaker', id: 53 },
  { name: 'Zangarmarsh', id: 53 },
  { name: 'Wildhammer', id: 53 },
  { name: 'Eredar', id: 53 },
  { name: 'Kilrogg', id: 4 },
  { name: 'Winterhoof', id: 4 },
  { name: 'Eitrigg', id: 47 },
  { name: "Shu'halo", id: 47 },
  { name: 'Feathermoon', id: 118 },
  { name: 'Scarlet Crusade', id: 118 },
  { name: 'Proudmoore', id: 5 },
  { name: 'Silver Hand', id: 12 },
  { name: 'Thorium Brotherhood', id: 12 },
  { name: 'Farstriders', id: 12 },
  { name: 'Cairne', id: 1168 },
  { name: 'Cenarius', id: 1168 },
  { name: 'Frostmane', id: 1168 },
  { name: 'Tortheldrin', id: 1168 },
  { name: "Ner'zhul", id: 1168 },
  { name: 'Korgath', id: 1168 },
  { name: 'Perenolde', id: 1168 },
  { name: 'Wyrmrest Accord', id: 1171 },
  { name: 'Aegwynn', id: 1136 },
  { name: 'Gurubashi', id: 1136 },
  { name: 'Bonechewer', id: 1136 },
  { name: 'Hakkar', id: 1136 },
  { name: 'Garrosh', id: 1136 },
  { name: 'Daggerspine', id: 1136 },
  { name: 'Emerald Dream', id: 162 },
  { name: 'Blackhand', id: 54 },
  { name: 'Galakrond', id: 54 },
  { name: 'Whisperwind', id: 55 },
  { name: 'Dentarg', id: 55 },
  { name: 'Stormrage', id: 60 },
  { name: 'Durotan', id: 63 },
  { name: 'Ysera', id: 63 },
  { name: 'Bloodhoof', id: 64 },
  { name: 'Duskwood', id: 64 },
  { name: 'Rexxar', id: 1151 },
  { name: 'Misha', id: 1151 },
  { name: 'Staghelm', id: 160 },
  { name: 'Dawnbringer', id: 160 },
  { name: 'Madoran', id: 160 },
  { name: 'Azuremyst', id: 160 },
  { name: 'Illidan', id: 57 },
  { name: 'Sargeras', id: 76 },
  { name: 'Azgalor', id: 77 },
  { name: 'Thunderlord', id: 77 },
  { name: 'Destromath', id: 77 },
  { name: 'Blood Furnace', id: 77 },
  { name: 'Mannoroth', id: 77 },
  { name: 'Nazjatar', id: 77 },
  { name: 'Azshara', id: 77 },
  { name: 'Magtheridon', id: 78 },
  { name: 'Anetheron', id: 78 },
  { name: 'Ysondre', id: 78 },
  { name: 'Altar of Storms', id: 78 },
  { name: 'Drakkari', id: 1425 },
  { name: 'Aerie Peak', id: 1426 },
  { name: 'Ragnaros', id: 1427 },
  { name: 'Shadow Council', id: 125 },
  { name: 'Sisters of Elune', id: 125 },
  { name: 'Cenarion Circle', id: 125 },
  { name: 'Blackwater Raiders', id: 125 },
  { name: 'Alexstrasza', id: 1070 },
  { name: 'Terokkar', id: 1070 },
  { name: 'Kirin Tor', id: 1071 },
  { name: 'Steamwheedle Cartel', id: 1071 },
  { name: 'Sentinels', id: 1071 },
  { name: 'Kul Tiras', id: 1147 },
  { name: 'Bladefist', id: 1147 },
  { name: "Zul'jin", id: 61 },
  { name: 'Maelstrom', id: 163 },
  { name: 'Twisting Nether', id: 163 },
  { name: 'Lightninghoof', id: 163 },
  { name: 'The Venture Co', id: 163 },
  { name: 'Ravenholdt', id: 163 },
  { name: 'Kalecgos', id: 155 },
  { name: 'Shattered Halls', id: 155 },
  { name: 'Executus', id: 155 },
  { name: 'Deathwing', id: 155 },
  { name: 'Dark Iron', id: 157 },
  { name: 'Shattered Hand', id: 157 },
  { name: 'Coilfang', id: 157 },
  { name: 'Demon Soul', id: 157 },
  { name: 'Dalvengyr', id: 157 },
  { name: 'Agamaggan', id: 1129 },
  { name: 'Kargath', id: 1129 },
  { name: 'Burning Legion', id: 1129 },
  { name: 'Thunderhorn', id: 1129 },
  { name: 'The Underbog', id: 1129 },
  { name: "Blade's Edge", id: 1129 },
  { name: 'Archimonde', id: 1129 },
  { name: 'Norgannon', id: 1129 },
  { name: 'Jaedenar', id: 1129 },
  { name: 'Baelgun', id: 1190 },
  { name: 'Doomhammer', id: 1190 },
  { name: 'Tichondrius', id: 11 },
  { name: 'Suramar', id: 113 },
  { name: 'Windrunner', id: 113 },
  { name: 'Darrowmere', id: 113 },
  { name: 'Draka', id: 113 },
  { name: 'Alleria', id: 52 },
  { name: 'Exodar', id: 52 },
  { name: 'Medivh', id: 52 },
  { name: 'Khadgar', id: 52 },
  { name: 'Arthas', id: 69 },
  { name: 'Detheroc', id: 154 },
  { name: 'Dethecus', id: 154 },
  { name: 'Lethon', id: 154 },
  { name: 'Blackwing Lair', id: 154 },
  { name: 'Shadowmoon', id: 154 },
  { name: 'Haomarush', id: 154 },
  { name: 'Gallywix', id: 3234 },
  { name: 'Greymane', id: 158 },
  { name: 'Tanaris', id: 158 },
  { name: "Kil'jaeden", id: 9 },
  { name: 'Darkspear', id: 120 },
  { name: 'Bronzebeard', id: 117 },
  { name: 'Shandris', id: 117 },
  { name: 'Chromaggus', id: 1138 },
  { name: 'Nathrezim', id: 1138 },
  { name: 'Smolderthorn', id: 1138 },
  { name: "Anub'arak", id: 1138 },
  { name: 'Arathor', id: 1138 },
  { name: 'Garithos', id: 1138 },
  { name: 'Drenden', id: 1138 },
  { name: 'Crushridge', id: 1138 },
  { name: 'Warsong', id: 71 },
  { name: 'Gorgonnash', id: 71 },
  { name: 'The Forgotten Coast', id: 71 },
  { name: 'Balnazzar', id: 71 },
  { name: 'Alterac Mountains', id: 71 },
  { name: 'Undermine', id: 71 },
  { name: 'Anvilmar', id: 71 },
  { name: "Quel'Thalas", id: 1428 },
  { name: 'Goldrinn', id: 3207 },
  { name: 'Nemesis', id: 3208 },
  { name: 'Tol Barad', id: 3208 },
  { name: 'Azralon', id: 3209 },
  { name: 'Dalaran', id: 3683 },
  { name: "Mal'Ganis", id: 3684 },
  { name: 'Turalyon', id: 3685 },
  { name: 'Moon Guard', id: 3675 },
  { name: 'Area 52', id: 3676 },
  { name: 'Hyjal', id: 3661 },
  { name: "Kel'Thuzad", id: 3693 },
  { name: 'Lightbringer', id: 3694 },
  { name: 'Caelestrasz', id: 3721 },
  { name: 'Nagrand', id: 3721 },
  { name: 'Saurfang', id: 3721 },
  { name: 'Barthilas', id: 3723 },
  { name: 'Frostmourne', id: 3725 },
  { name: 'Dreadmaul', id: 3725 },
  { name: 'Thaurissan', id: 3725 },
  { name: "Jubei'Thos", id: 3725 },
  { name: 'Gundrak', id: 3725 },
  { name: "Khaz'goroth", id: 3726 },
  { name: "Aman'Thul", id: 3726 },
  { name: "Dath'Remar", id: 3726 }
]

const EUData: Array<WoWServerData> = [
  { name: 'Thrall', id: 604 },
  { name: 'Khadgar', id: 1080 },
  { name: 'Bloodhoof', id: 1080 },
  { name: 'Dentarg', id: 1084 },
  { name: 'Tarren Mill', id: 1084 },
  { name: 'Karazhan', id: 1596 },
  { name: 'Dragonblight', id: 1596 },
  { name: 'The Maelstrom', id: 1596 },
  { name: 'Ghostlands', id: 1596 },
  { name: "Lightning's Blade", id: 1596 },
  { name: 'Deathwing', id: 1596 },
  { name: 'Auchindoun', id: 1597 },
  { name: 'Dunemaul', id: 1597 },
  { name: 'Sylvanas', id: 1597 },
  { name: 'Jaedenar', id: 1597 },
  { name: 'Shattered Halls', id: 1598 },
  { name: 'Chromaggus', id: 1598 },
  { name: 'Sunstrider', id: 1598 },
  { name: 'Balnazzar', id: 1598 },
  { name: 'Talnivarr', id: 1598 },
  { name: "Ahn'Qiraj", id: 1598 },
  { name: 'Daggerspine', id: 1598 },
  { name: 'Laughing Skull', id: 1598 },
  { name: 'Trollbane', id: 1598 },
  { name: 'Boulderfist', id: 1598 },
  { name: 'Gordunni', id: 1602 },
  { name: 'Soulflayer', id: 1604 },
  { name: 'Deathguard', id: 1605 },
  { name: 'Galakrond', id: 1614 },
  { name: 'Deepholm', id: 1614 },
  { name: 'Razuvious', id: 1614 },
  { name: 'Kargath', id: 604 },
  { name: 'Ambossar', id: 604 },
  { name: 'Emeriss', id: 1091 },
  { name: "Twilight's Hammer", id: 1091 },
  { name: 'Bloodscalp', id: 1091 },
  { name: 'Crushridge', id: 1091 },
  { name: 'Agamaggan', id: 1091 },
  { name: 'Hakkar', id: 1091 },
  { name: "Drak'thul", id: 1092 },
  { name: 'Burning Blade', id: 1092 },
  { name: 'Ysera', id: 1097 },
  { name: 'Malorne', id: 1097 },
  { name: 'Malygos', id: 1098 },
  { name: 'Malfurion', id: 1098 },
  { name: 'Anetheron', id: 1104 },
  { name: "Kil'jaeden", id: 1104 },
  { name: 'Rajaxx', id: 1104 },
  { name: 'Festung der St\u00fcrme', id: 1104 },
  { name: "Gul'dan", id: 1104 },
  { name: 'Nathrezim', id: 1104 },
  { name: 'Nazjatar', id: 1105 },
  { name: 'Zuluhed', id: 1105 },
  { name: 'Dalvengyr', id: 1105 },
  { name: "Aman'Thul", id: 1105 },
  { name: 'Frostmourne', id: 1105 },
  { name: "Anub'arak", id: 1105 },
  { name: 'Die Arguswacht', id: 1121 },
  { name: 'Die ewige Wacht', id: 1121 },
  { name: 'Die Todeskrallen', id: 1121 },
  { name: 'Das Syndikat', id: 1121 },
  { name: 'Der abyssische Rat', id: 1121 },
  { name: 'Kult der Verdammten', id: 1121 },
  { name: 'Das Konsortium', id: 1121 },
  { name: 'Die Silberne Hand', id: 1121 },
  { name: 'Uldaman', id: 1122 },
  { name: "Drek'Thar", id: 1122 },
  { name: 'Krasus', id: 1122 },
  { name: 'Eitrigg', id: 1122 },
  { name: 'Confr\u00e9rie du Thorium', id: 1127 },
  { name: 'La Croisade \u00e9carlate', id: 1127 },
  { name: 'Culte de la Rive noire', id: 1127 },
  { name: 'Les Sentinelles', id: 1127 },
  { name: 'Kirin Tor', id: 1127 },
  { name: 'Les Clairvoyants', id: 1127 },
  { name: 'Conseil des Ombres', id: 1127 },
  { name: 'Turalyon', id: 1402 },
  { name: 'Doomhammer', id: 1402 },
  { name: "Blade's Edge", id: 1416 },
  { name: 'Eonar', id: 1416 },
  { name: "Vek'nilash", id: 1416 },
  { name: 'Aerie Peak', id: 1416 },
  { name: 'Bronzebeard', id: 1416 },
  { name: 'Dethecus', id: 531 },
  { name: 'Theradras', id: 531 },
  { name: 'Onyxia', id: 531 },
  { name: "Mug'thol", id: 531 },
  { name: 'Terrordar', id: 531 },
  { name: "Vol'jin", id: 510 },
  { name: 'Chants \u00e9ternels', id: 510 },
  { name: 'Arak-arahm', id: 512 },
  { name: 'Rashgarroth', id: 512 },
  { name: "Kael'thas", id: 512 },
  { name: "Throk'Feroth", id: 512 },
  { name: 'Nefarian', id: 612 },
  { name: 'Gilneas', id: 612 },
  { name: 'Destromath', id: 612 },
  { name: 'Ulduar', id: 612 },
  { name: 'Mannoroth', id: 612 },
  { name: 'Gorgonnash', id: 612 },
  { name: "Nera'thor", id: 612 },
  { name: "Kor'gall", id: 633 },
  { name: 'Executus', id: 633 },
  { name: 'Shattered Hand', id: 633 },
  { name: 'Bloodfeather', id: 633 },
  { name: 'Terokkar', id: 633 },
  { name: 'Saurfang', id: 633 },
  { name: 'Darkspear', id: 633 },
  { name: 'Burning Steppes', id: 633 },
  { name: 'Suramar', id: 1331 },
  { name: 'Medivh', id: 1331 },
  { name: 'Garrosh', id: 1401 },
  { name: 'Shattrath', id: 1401 },
  { name: 'Nozdormu', id: 1401 },
  { name: 'Perenolde', id: 1401 },
  { name: 'Teldrassil', id: 1401 },
  { name: 'Draenor', id: 1403 },
  { name: 'Arygos', id: 1406 },
  { name: "Khaz'goroth", id: 1406 },
  { name: 'Mar\u00e9cage de Zangar', id: 1621 },
  { name: "Cho'gall", id: 1621 },
  { name: "Eldre'Thalas", id: 1621 },
  { name: 'Sinstralis', id: 1621 },
  { name: 'Dalaran', id: 1621 },
  { name: 'Naxxramas', id: 1624 },
  { name: 'Arathi', id: 1624 },
  { name: 'Illidan', id: 1624 },
  { name: 'Temple noir', id: 1624 },
  { name: 'Arthas', id: 578 },
  { name: 'Blutkessel', id: 578 },
  { name: 'Wrathbringer', id: 578 },
  { name: 'Durotan', id: 578 },
  { name: "Kel'Thuzad", id: 578 },
  { name: "Vek'lor", id: 578 },
  { name: 'Tirion', id: 578 },
  { name: 'Blackmoore', id: 580 },
  { name: 'Tichondrius', id: 580 },
  { name: 'Lordaeron', id: 580 },
  { name: 'Howling Fjord', id: 1615 },
  { name: 'Chamber of Aspects', id: 1307 },
  { name: "Pozzo dell'Eternit\u00e0", id: 1309 },
  { name: 'Blackrock', id: 581 },
  { name: 'Garona', id: 509 },
  { name: 'Sargeras', id: 509 },
  { name: "Ner'zhul", id: 509 },
  { name: 'Aggramar', id: 1325 },
  { name: 'Hellscream', id: 1325 },
  { name: 'Ravencrest', id: 1329 },
  { name: 'Ysondre', id: 1335 },
  { name: 'Wildhammer', id: 1313 },
  { name: 'Thunderhorn', id: 1313 },
  { name: 'Nemesis', id: 1316 },
  { name: 'Fordragon', id: 1623 },
  { name: 'Lothar', id: 570 },
  { name: 'Baelgun', id: 570 },
  { name: 'Azshara', id: 570 },
  { name: "Krag'jin", id: 570 },
  { name: 'Scarshield Legion', id: 1096 },
  { name: 'Sporeggar', id: 1096 },
  { name: 'Earthen Ring', id: 1096 },
  { name: 'Defias Brotherhood', id: 1096 },
  { name: 'Ravenholdt', id: 1096 },
  { name: 'Darkmoon Faire', id: 1096 },
  { name: 'The Venture Co', id: 1096 },
  { name: 'Kul Tiras', id: 1082 },
  { name: 'Alonsus', id: 1082 },
  { name: 'Anachronos', id: 1082 },
  { name: 'Dun Modr', id: 1378 },
  { name: "C'Thun", id: 1378 },
  { name: "Zul'jin", id: 1379 },
  { name: 'Uldum', id: 1379 },
  { name: 'Sanguino', id: 1379 },
  { name: "Shen'dralar", id: 1379 },
  { name: 'Tyrande', id: 1384 },
  { name: 'Los Errantes', id: 1384 },
  { name: 'Colinas Pardas', id: 1384 },
  { name: 'Exodar', id: 1385 },
  { name: 'Minahonda', id: 1385 },
  { name: 'Lightbringer', id: 1388 },
  { name: 'Mazrigos', id: 1388 },
  { name: 'Bronze Dragonflight', id: 1393 },
  { name: 'Nordrassil', id: 1393 },
  { name: "Quel'Thalas", id: 1396 },
  { name: 'Azjol-Nerub', id: 1396 },
  { name: "Un'Goro", id: 1400 },
  { name: "Sen'jin", id: 1400 },
  { name: 'Area 52', id: 1400 },
  { name: 'Rexxar', id: 1099 },
  { name: 'Alleria', id: 1099 },
  { name: 'Die Aldor', id: 1618 },
  { name: 'Hyjal', id: 1390 },
  { name: 'Eversong', id: 1925 },
  { name: 'Goldrinn', id: 1928 },
  { name: 'Lich King', id: 1928 },
  { name: 'Greymane', id: 1928 },
  { name: 'Blackscar', id: 1929 },
  { name: 'Deathweaver', id: 1929 },
  { name: 'Borean Tundra', id: 1929 },
  { name: 'Thermaplugg', id: 1929 },
  { name: 'Grom', id: 1929 },
  { name: 'Booty Bay', id: 1929 },
  { name: 'Todeswache', id: 1405 },
  { name: 'Zirkel des Cenarius', id: 1405 },
  { name: 'Der Mithrilorden', id: 1405 },
  { name: 'Forscherliga', id: 1405 },
  { name: 'Der Rat von Dalaran', id: 1405 },
  { name: 'Die Nachtwache', id: 1405 },
  { name: 'Azuremyst', id: 1417 },
  { name: 'Stormrage', id: 1417 },
  { name: 'Stormscale', id: 2073 },
  { name: 'Terenas', id: 2074 },
  { name: 'Emerald Dream', id: 2074 },
  { name: 'Archimonde', id: 1302 },
  { name: 'Grim Batol', id: 1303 },
  { name: 'Aggra (Portugu\u00eas)', id: 1303 },
  { name: 'Frostmane', id: 1303 },
  { name: 'Kazzak', id: 1305 },
  { name: 'Moonglade', id: 1085 },
  { name: 'Steamwheedle Cartel', id: 1085 },
  { name: "The Sha'tar", id: 1085 },
  { name: 'Elune', id: 1315 },
  { name: 'Varimathras', id: 1315 },
  { name: 'Hellfire', id: 1587 },
  { name: 'Runetotem', id: 1587 },
  { name: 'Arathor', id: 1587 },
  { name: 'Kilrogg', id: 1587 },
  { name: 'Nagrand', id: 1587 },
  { name: 'Outland', id: 1301 },
  { name: 'Azuregos', id: 1922 },
  { name: 'Ashenvale', id: 1923 },
  { name: 'Norgannon', id: 1408 },
  { name: 'Dun Morogh', id: 1408 },
  { name: 'Silvermoon', id: 3391 },
  { name: 'Spinebreaker', id: 3656 },
  { name: 'Dragonmaw', id: 3656 },
  { name: 'Vashj', id: 3656 },
  { name: 'Stormreaver', id: 3656 },
  { name: 'Haomarush', id: 3656 },
  { name: 'Genjuros', id: 3657 },
  { name: 'Zenedar', id: 3657 },
  { name: 'Bladefist', id: 3657 },
  { name: 'Neptulon', id: 3657 },
  { name: 'Frostwhisper', id: 3657 },
  { name: 'Darksorrow', id: 3657 },
  { name: 'Shadowsong', id: 3666 },
  { name: 'Aszune', id: 3666 },
  { name: 'Argent Dawn', id: 3702 },
  { name: 'Frostwolf', id: 3703 },
  { name: "Al'Akir", id: 3713 },
  { name: 'Skullcrusher', id: 3713 },
  { name: 'Xavius', id: 3713 },
  { name: 'Burning Legion', id: 3713 },
  { name: 'Twisting Nether', id: 3674 },
  { name: 'Aegwynn', id: 3679 },
  { name: 'Magtheridon', id: 3681 },
  { name: 'Ragnaros', id: 3682 },
  { name: 'Antonidas', id: 3686 },
  { name: 'Khaz Modan', id: 3690 },
  { name: 'Echsenkessel', id: 3691 },
  { name: 'Blackhand', id: 3691 },
  { name: "Mal'Ganis", id: 3691 },
  { name: 'Taerar', id: 3691 },
  { name: 'Eredar', id: 3692 },
  { name: 'Nethersturm', id: 3696 },
  { name: 'Alexstrasza', id: 3696 },
  { name: 'Madmortem', id: 3696 },
  { name: 'Proudmoore', id: 3696 }
]

export const findWoWServersIdByName = (
  term: string,
  region: 'NA' | 'EU' = 'NA'
) => {
  const data = region === 'NA' ? NAdata : EUData
  return data.filter(({ name }) =>
    name.toLowerCase().includes(term.toLowerCase())
  )
}

export const findRegionByWorldId = (worldId: number) => {
  const isEu = EUData.find(({ id }) => id === worldId)

  return isEu ? 'EU' : 'NA'
}

export const findNAWoWServerByID = (idToFind: number) => {
  return NAdata.find(({ id }) => id === idToFind)
}

/**
 * Fetches WoW server information based on region and server details.
 * @example
 * functionName('EU', '1234', 'Darkspear')
 * { server: { name: 'Darkspear', id: 1234 }, region: 'EU' }
 * @param {WoWServerRegion} region - The region code ('EU' or 'NA') to look up.
 * @param {number|string|undefined} serverId - The ID of the server, which can be a number or a string representing a number.
 * @param {string|undefined} serverName - The name of the server.
 * @returns {{server: {name: string, id: number}, region: string}} An object containing the server details and region code.
 * @description
 *   - Parses the serverId if it is provided as a string to ensure correct filtering.
 *   - Defaults to server 'Thrall' with ID 3678 in 'NA' region if server is not found.
 *   - Utilizes different data sources based on the specified region.
 */
export const validateServerAndRegion = (
  region: WoWServerRegion,
  serverId: number | string | undefined,
  serverName: string | undefined
) => {
  const data = region === 'EU' ? EUData : NAdata

  const serverIdToCompare =
    typeof serverId === 'string' ? parseInt(serverId, 10) : serverId

  const servers = data.filter(({ id }) => id === serverIdToCompare)
  const server = servers.find(({ name }) => name === serverName)

  if (server) {
    return { server, region }
  } else {
    // If server not found in requested region, find a default server in that region
    const defaultServer = data[0] // Use the first server in the region
    return {
      server: defaultServer,
      region: region
    }
  }
}
