export const data = [
  { name: 'Azjol-Nerub', id: 121 },
  { name: 'Muradin', id: 121 },
  { name: 'Nordrassil', id: 121 },
  { name: 'Blackrock', id: 121 },
  { name: 'Khaz Modan', id: 121 },
  { name: 'Firetree', id: 127 },
  { name: "Drak'Tharon", id: 127 },
  { name: 'Rivendare', id: 127 },
  { name: 'Vashj', id: 127 },
  { name: 'Spirestone', id: 127 },
  { name: 'Malorne', id: 127 },
  { name: 'Frostwolf', id: 127 },
  { name: 'Stormscale', id: 127 },
  { name: 'Runetotem', id: 151 },
  { name: 'Uther', id: 151 },
  { name: 'Draenor', id: 115 },
  { name: 'Echo Isles', id: 115 },
  { name: 'Aggramar', id: 106 },
  { name: 'Fizzcrank', id: 106 },
  { name: 'Ravencrest', id: 1072 },
  { name: 'Uldaman', id: 1072 },
  { name: 'Stormreaver', id: 58 },
  { name: 'Elune', id: 67 },
  { name: 'Laughing Skull', id: 67 },
  { name: 'Auchindoun', id: 67 },
  { name: "Cho'gall", id: 67 },
  { name: 'Gilneas', id: 67 },
  { name: 'Bleeding Hollow', id: 73 },
  { name: 'Trollbane', id: 1175 },
  { name: 'Grizzly Hills', id: 1175 },
  { name: 'Malfurion', id: 1175 },
  { name: 'Lothar', id: 1175 },
  { name: "Kael'thas", id: 1175 },
  { name: 'Gnomeregan', id: 1175 },
  { name: 'Moonrunner', id: 1175 },
  { name: 'Ghostlands', id: 1175 },
  { name: "Vek'nilash", id: 1184 },
  { name: 'Nazgrel', id: 1184 },
  { name: 'Nesingwary', id: 1184 },
  { name: "Sen'jin", id: 1185 },
  { name: 'Dunemaul', id: 1185 },
  { name: 'Maiev', id: 1185 },
  { name: 'Bloodscalp', id: 1185 },
  { name: "Quel'dorei", id: 1185 },
  { name: 'Boulderfist', id: 1185 },
  { name: 'Stonemaul', id: 1185 },
  { name: 'Argent Dawn', id: 75 },
  { name: 'The Scryers', id: 75 },
  { name: 'Dragonmaw', id: 84 },
  { name: 'Uldum', id: 84 },
  { name: 'Akama', id: 84 },
  { name: 'Korialstrasz', id: 84 },
  { name: "Eldre'Thalas", id: 84 },
  { name: "Mug'thol", id: 84 },
  { name: 'Antonidas', id: 84 },
  { name: 'Silvermoon', id: 86 },
  { name: 'Skywall', id: 86 },
  { name: 'Terenas', id: 86 },
  { name: 'Hydraxis', id: 86 },
  { name: "Drak'thul", id: 86 },
  { name: 'Borean Tundra', id: 86 },
  { name: "Mok'Nathal", id: 86 },
  { name: 'Shadowsong', id: 86 },
  { name: 'Eonar', id: 96 },
  { name: 'Skullcrusher', id: 96 },
  { name: "Gul'dan", id: 96 },
  { name: 'Zuluhed', id: 96 },
  { name: 'Ursin', id: 96 },
  { name: 'Andorhal', id: 96 },
  { name: 'Black Dragonflight', id: 96 },
  { name: 'Velen', id: 96 },
  { name: 'Scilla', id: 96 },
  { name: 'Llane', id: 99 },
  { name: 'Arygos', id: 99 },
  { name: 'Earthen Ring', id: 100 },
  { name: 'Malygos', id: 104 },
  { name: 'Garona', id: 104 },
  { name: "Lightning's Blade", id: 104 },
  { name: 'Icecrown', id: 104 },
  { name: 'Onyxia', id: 104 },
  { name: 'Burning Blade', id: 104 },
  { name: 'Dragonblight', id: 114 },
  { name: 'Fenris', id: 114 },
  { name: 'Hellscream', id: 53 },
  { name: 'Gorefiend', id: 53 },
  { name: 'Spinebreaker', id: 53 },
  { name: 'Zangarmarsh', id: 53 },
  { name: 'Wildhammer', id: 53 },
  { name: 'Eredar', id: 53 },
  { name: 'Kilrogg', id: 4 },
  { name: 'Winterhoof', id: 4 },
  { name: 'Eitrigg', id: 47 },
  { name: "Shu'halo", id: 47 },
  { name: 'Feathermoon', id: 118 },
  { name: 'Scarlet Crusade', id: 118 },
  { name: 'Proudmoore', id: 5 },
  { name: 'Silver Hand', id: 12 },
  { name: 'Thorium Brotherhood', id: 12 },
  { name: 'Farstriders', id: 12 },
  { name: 'Cairne', id: 1168 },
  { name: 'Cenarius', id: 1168 },
  { name: 'Frostmane', id: 1168 },
  { name: 'Tortheldrin', id: 1168 },
  { name: "Ner'zhul", id: 1168 },
  { name: 'Korgath', id: 1168 },
  { name: 'Perenolde', id: 1168 },
  { name: 'Wyrmrest Accord', id: 1171 },
  { name: 'Aegwynn', id: 1136 },
  { name: 'Gurubashi', id: 1136 },
  { name: 'Bonechewer', id: 1136 },
  { name: 'Hakkar', id: 1136 },
  { name: 'Garrosh', id: 1136 },
  { name: 'Daggerspine', id: 1136 },
  { name: 'Emerald Dream', id: 162 },
  { name: 'Blackhand', id: 54 },
  { name: 'Galakrond', id: 54 },
  { name: 'Whisperwind', id: 55 },
  { name: 'Dentarg', id: 55 },
  { name: 'Stormrage', id: 60 },
  { name: 'Durotan', id: 63 },
  { name: 'Ysera', id: 63 },
  { name: 'Bloodhoof', id: 64 },
  { name: 'Duskwood', id: 64 },
  { name: 'Rexxar', id: 1151 },
  { name: 'Misha', id: 1151 },
  { name: 'Staghelm', id: 160 },
  { name: 'Dawnbringer', id: 160 },
  { name: 'Madoran', id: 160 },
  { name: 'Azuremyst', id: 160 },
  { name: 'Illidan', id: 57 },
  { name: 'Sargeras', id: 76 },
  { name: 'Azgalor', id: 77 },
  { name: 'Thunderlord', id: 77 },
  { name: 'Destromath', id: 77 },
  { name: 'Blood Furnace', id: 77 },
  { name: 'Mannoroth', id: 77 },
  { name: 'Nazjatar', id: 77 },
  { name: 'Azshara', id: 77 },
  { name: 'Magtheridon', id: 78 },
  { name: 'Anetheron', id: 78 },
  { name: 'Ysondre', id: 78 },
  { name: 'Altar of Storms', id: 78 },
  { name: 'Drakkari', id: 1425 },
  { name: 'Aerie Peak', id: 1426 },
  { name: 'Ragnaros', id: 1427 },
  { name: 'Shadow Council', id: 125 },
  { name: 'Sisters of Elune', id: 125 },
  { name: 'Cenarion Circle', id: 125 },
  { name: 'Blackwater Raiders', id: 125 },
  { name: 'Alexstrasza', id: 1070 },
  { name: 'Terokkar', id: 1070 },
  { name: 'Kirin Tor', id: 1071 },
  { name: 'Steamwheedle Cartel', id: 1071 },
  { name: 'Sentinels', id: 1071 },
  { name: 'Kul Tiras', id: 1147 },
  { name: 'Bladefist', id: 1147 },
  { name: "Zul'jin", id: 61 },
  { name: 'Maelstrom', id: 163 },
  { name: 'Twisting Nether', id: 163 },
  { name: 'Lightninghoof', id: 163 },
  { name: 'The Venture Co', id: 163 },
  { name: 'Ravenholdt', id: 163 },
  { name: 'Kalecgos', id: 155 },
  { name: 'Shattered Halls', id: 155 },
  { name: 'Executus', id: 155 },
  { name: 'Deathwing', id: 155 },
  { name: 'Dark Iron', id: 157 },
  { name: 'Shattered Hand', id: 157 },
  { name: 'Coilfang', id: 157 },
  { name: 'Demon Soul', id: 157 },
  { name: 'Dalvengyr', id: 157 },
  { name: 'Agamaggan', id: 1129 },
  { name: 'Kargath', id: 1129 },
  { name: 'Burning Legion', id: 1129 },
  { name: 'Thunderhorn', id: 1129 },
  { name: 'The Underbog', id: 1129 },
  { name: "Blade's Edge", id: 1129 },
  { name: 'Archimonde', id: 1129 },
  { name: 'Norgannon', id: 1129 },
  { name: 'Jaedenar', id: 1129 },
  { name: 'Baelgun', id: 1190 },
  { name: 'Doomhammer', id: 1190 },
  { name: 'Tichondrius', id: 11 },
  { name: 'Suramar', id: 113 },
  { name: 'Windrunner', id: 113 },
  { name: 'Darrowmere', id: 113 },
  { name: 'Draka', id: 113 },
  { name: 'Alleria', id: 52 },
  { name: 'Exodar', id: 52 },
  { name: 'Medivh', id: 52 },
  { name: 'Khadgar', id: 52 },
  { name: 'Arthas', id: 69 },
  { name: 'Detheroc', id: 154 },
  { name: 'Dethecus', id: 154 },
  { name: 'Lethon', id: 154 },
  { name: 'Blackwing Lair', id: 154 },
  { name: 'Shadowmoon', id: 154 },
  { name: 'Haomarush', id: 154 },
  { name: 'Gallywix', id: 3234 },
  { name: 'Greymane', id: 158 },
  { name: 'Tanaris', id: 158 },
  { name: "Kil'jaeden", id: 9 },
  { name: 'Darkspear', id: 120 },
  { name: 'Bronzebeard', id: 117 },
  { name: 'Shandris', id: 117 },
  { name: 'Chromaggus', id: 1138 },
  { name: 'Nathrezim', id: 1138 },
  { name: 'Smolderthorn', id: 1138 },
  { name: "Anub'arak", id: 1138 },
  { name: 'Arathor', id: 1138 },
  { name: 'Garithos', id: 1138 },
  { name: 'Drenden', id: 1138 },
  { name: 'Crushridge', id: 1138 },
  { name: 'Warsong', id: 71 },
  { name: 'Gorgonnash', id: 71 },
  { name: 'The Forgotten Coast', id: 71 },
  { name: 'Balnazzar', id: 71 },
  { name: 'Alterac Mountains', id: 71 },
  { name: 'Undermine', id: 71 },
  { name: 'Anvilmar', id: 71 },
  { name: "Quel'Thalas", id: 1428 },
  { name: 'Goldrinn', id: 3207 },
  { name: 'Nemesis', id: 3208 },
  { name: 'Tol Barad', id: 3208 },
  { name: 'Azralon', id: 3209 },
  { name: 'Dalaran', id: 3683 },
  { name: "Mal'Ganis", id: 3684 },
  { name: 'Turalyon', id: 3685 },
  { name: 'Moon Guard', id: 3675 },
  { name: 'Area 52', id: 3676 },
  { name: 'Thrall', id: 3678 },
  { name: 'Hyjal', id: 3661 },
  { name: "Kel'Thuzad", id: 3693 },
  { name: 'Lightbringer', id: 3694 },
  { name: 'Caelestrasz', id: 3721 },
  { name: 'Nagrand', id: 3721 },
  { name: 'Saurfang', id: 3721 },
  { name: 'Barthilas', id: 3723 },
  { name: 'Frostmourne', id: 3725 },
  { name: 'Dreadmaul', id: 3725 },
  { name: 'Thaurissan', id: 3725 },
  { name: "Jubei'Thos", id: 3725 },
  { name: 'Gundrak', id: 3725 },
  { name: "Khaz'goroth", id: 3726 },
  { name: "Aman'Thul", id: 3726 },
  { name: "Dath'Remar", id: 3726 }
]

export const findWoWServersIdByName = (term: string) => {
  return data.filter(({ name }) =>
    name.toLowerCase().includes(term.toLowerCase())
  )
}
