---
name: "Unit Tests"

on: push

jobs:
  "Run Jest":
    runs-on: ubuntu-latest
    container: node:20.3.0

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install
      - name: Run Tests
        run: yarn test
